---
title: "Eelgrass GO Fitness Comparison Plotting"
author: "Camille Rumberger"
date: "`r Sys.Date()`"
output: html_document
---

# Genomic-Offset Fitness-Offset Plotting

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/Documents/GitHub/BalticEelgrass")

# packages
library(tidyverse)
library(dplyr)
library(ggplot2)
library(stringr)
library(forcats)

# data
# exp fit
surv_go <- read.csv("results/GO_compare/survival_offset_avgs.csv")
surv_all_go <- read.csv("results/GO_compare/survival_offset_binary.csv")
grow_go <- read.csv("results/GO_compare/grow_offset.csv")
surv_corrs_cf <- read.csv("results/GO_compare/surv_corrs_cf.csv")[,-1]
surv_corrs_cg <- read.csv("results/GO_compare/surv_corrs_cg.csv")[,-1]
grow_corrs_cf <- read.csv("results/GO_compare/grow_corr_cf.csv")[,-1]
grow_corrs_cg <- read.csv("results/GO_compare/grow_corr_cg.csv")[,-1]
```

## Data Cleaning & Setup

```{r}
# add pop coast and trt coast to all dfs for plotting
pop_coast <- data.frame(pop = c("VIK","VAT","HOG","BAR",
                                "KUR","KAL","HOR","BJO"),
                        pop_ord = 1:8,
                        pop_coast = c("West", "West", "West", "West", 
                                      "East", "East", "East", "East"),
                        pop_coast_ord = c(1,1,1,1,2,2,2,2))
trt_coast <- data.frame(trt = c("TempControl-21psu", "TempControl-7psu", 
                                "TempWarm-16psu", "TempWarm-5psu"),
                        trt_ord = 1:4,
                        trt_coast = c("West", "East", "West", "East"),
                        trt_coast_ord = c(1,2,1,2))
surv_go1 <- merge(surv_go, pop_coast, by = "pop")
surv_go2 <- merge(surv_go1, trt_coast, by = "trt")

surv_all_go1 <- merge(surv_all_go, pop_coast, by = "pop")
surv_all_go2 <- merge(surv_all_go1, trt_coast, by = "trt")

grow_go1 <- merge(grow_go, pop_coast, by = "pop")
grow_go2 <- merge(grow_go1, trt_coast, by = "trt")

# full vs mll (plotting)
surv_go_full <- surv_go2[surv_go2$cc == "full",]
surv_go_mll <- surv_go2[surv_go2$cc == "mll",]
surv_all_go_full <- surv_all_go2[surv_all_go2$cc == "full",]
surv_all_go_mll <- surv_all_go2[surv_all_go2$cc == "mll",]
grow_go_full <- grow_go2[grow_go2$cc == "full",]
grow_go_mll <- grow_go2[grow_go2$cc == "mll",]

# significant lines code
#geom_smooth(method = "lm", data = fullfit[fullfit$bag_site == "YorkRiver" & fullfit$event == 4,], aes(x = offset_lea_go_yrk, y = surv), col = "purple4", fill = "purple4", se = T, linetype = ifelse(corrs_df[corrs_df$method == "lea" & corrs_df$biotic == "b" & corrs_df$sel == "sel" & corrs_df$bag_site == "YorkRiver" & corrs_df$event == 4,]$signif_surv_adj == T, "solid", "dashed")) +
```

## Plotting

### Survival

LEA

```{r}
# means by pop/treatment
# common garden: Env Dist
####################
surv_full_cg_env <- surv_go_full %>% ggplot(aes(x = env_dist, y = surv, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "lm", se = T) + 
  labs(title = "Common Garden Fitness vs Environmental Distance (Full): Survival",
       x = "Environmental Distance", y = "Survival") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21)))+
  theme_minimal()
surv_full_cg_env
surv_mll_cg_env <- surv_go_mll %>% ggplot(aes(x = env_dist, y = surv, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "lm", se = T) + 
  labs(title = "Common Garden Fitness vs Environmental Distance (MLL): Survival",
       x = "Environmental Distance", y = "Survival") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21)))+
  theme_minimal()
surv_mll_cg_env
####################

# current future: Env Dist
#####################
surv_full_cf_env <- surv_go_full %>% ggplot(aes(x = env_dist, y = surv, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "lm", se = F) + 
  labs(title = "Current-Future Fitness vs Environmental Distance (Full): Survival", 
       x = "Environmental Distance", y = "Survival") +
  scale_fill_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
surv_full_cf_env
surv_mll_cf_env <- surv_go_mll %>% ggplot(aes(x = env_dist, y = surv, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "lm", se = F) + 
  labs(title = "Current-Future Fitness vs Environmental Distance (MLL): Survival", 
       x = "Environmental Distance", y = "Survival") +
  scale_fill_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
surv_mll_cf_env
#####################

# binary outcome
# common garden: Env Dist
####################
surv_full_bin_cg_env <- surv_all_go_full %>% 
  filter(method == "env") %>%
  ggplot(aes(x = offset, y = surv, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "lm", se = T) + 
  labs(title = "Common Garden Fitness vs Environmental Distance (Full): \nBinary Survival",
       x = "Environmental Distance", y = "Survival") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21)))+
  theme_minimal()
surv_full_bin_cg_env
surv_mll_bin_cg_env <- surv_all_go_mll %>% 
  filter(method == "env") %>%
  ggplot(aes(x = offset, y = surv, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "lm", se = T) + 
  labs(title = "Common Garden Fitness vs Environmental Distance (MLL): \nBinary Survival",
       x = "Environmental Distance", y = "Survival") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21)))+
  theme_minimal()
surv_mll_bin_cg_env
####################

# with log regression
#####################
surv_full_binlog_cg_env <- surv_all_go_full %>% 
  filter(method == "env") %>%
  ggplot(aes(x = offset, y = surv, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "glm", method.args = list(family = "binomial"), se = T) + 
  labs(title = "Common Garden Fitness vs Environmental Distance (Full): \nBinary Survival, Logistic Regression",
       x = "Environmental Distance", y = "Survival") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21)))+
  theme_minimal()
surv_full_binlog_cg_env

surv_mll_binlog_cg_env <- surv_all_go_mll %>% 
  filter(method == "env") %>%
  ggplot(aes(x = offset, y = surv, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "glm", method.args = list(family = "binomial"), se = T) + 
  labs(title = "Common Garden Fitness vs Environmental Distance (MLL): \nBinary Survival, Logistic Regression",
       x = "Environmental Distance", y = "Survival") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21)))+
  theme_minimal()
surv_mll_binlog_cg_env
#####################

# current future: Env Dist
#####################
surv_full_bin_cf_env <- surv_all_go_full %>%
  filter(method == "env") %>%
  ggplot(aes(x = offset, y = surv, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "lm", se = F) + 
  labs(title = "Current-Future Fitness vs Environmental Distance (Full): \nBinary Survival", 
       x = "Environmental Distance", y = "Survival") +
  scale_fill_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
surv_full_bin_cf_env

surv_mll_bin_cf_env <- surv_all_go_mll %>% 
  filter(method == "env") %>%
  ggplot(aes(x = offset, y = surv, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "lm", se = F) + 
  labs(title = "Current-Future Fitness vs Environmental Distance (MLL): \nBinary Survival", 
       x = "Environmental Distance", y = "Survival") +
  scale_fill_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
surv_mll_bin_cf_env
#####################

# with log regression
#####################
surv_full_binlog_cf_env <- surv_all_go_full %>%
  filter(method == "env") %>%
  ggplot(aes(x = offset, y = surv, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "glm", method.args = list(family = "binomial"), se = F) + 
  labs(title = "Current-Future Fitness vs Environmental Distance (Full): \nBinary Survival, Logistic Regression", 
       x = "Environmental Distance", y = "Survival") +
  scale_fill_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
surv_full_binlog_cf_env

surv_mll_binlog_cf_env <- surv_all_go_mll %>% 
  filter(method == "env") %>%
  ggplot(aes(x = offset, y = surv, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "glm", method.args = list(family = "binomial"), se = F) + 
  labs(title = "Current-Future Fitness vs Environmental Distance (MLL): \nBinary Survival, Logistic Regression", 
       x = "Environmental Distance", y = "Survival") +
  scale_fill_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
surv_mll_binlog_cf_env
#####################
```

RDA

```{r}
# common garden: RDA
####################
surv_full_cg_rda <- surv_go_full %>% 
  ggplot(aes(x = rda_offset, y = surv, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "lm", se = T) + 
  labs(title = "Common Garden Fitness vs Genomic Offset (RDA, Full): Survival",
       x = "RDA offset", y = "Survival") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21)))+
  theme_minimal()
surv_full_cg_rda

surv_mll_cg_rda <- surv_go_mll %>% ggplot(aes(x = rda_offset, y = surv, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "lm", se = T) + 
  labs(title = "Common Garden Fitness vs Genomic Offset (RDA, MLL): Survival",
       x = "RDA offset", y = "Survival") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21)))+
  theme_minimal()
surv_mll_cg_rda
####################

# current future: RDA
#####################
surv_full_cf_rda <- surv_go_full %>% ggplot(aes(x = rda_offset, y = surv, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "lm", se = F) + 
  labs(title = "Current-Future Fitness vs Genomic Offset (RDA, Full): Survival", 
       x = "RDA offset", y = "Survival") +
  scale_fill_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
surv_full_cf_rda

surv_mll_cf_rda <- surv_go_mll %>% ggplot(aes(x = rda_offset, y = surv, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "lm", se = F) + 
  labs(title = "Current-Future Fitness vs Genomic Offset (RDA, MLL): Survival", 
       x = "RDA offset", y = "Survival") +
  scale_fill_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
surv_mll_cf_rda
#####################

# binary
# common garden: RDA
####################
surv_full_bin_cg_rda <- surv_all_go_full %>% 
  filter(method == "rda") %>% 
  ggplot(aes(x = offset, y = surv, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "lm", se = T) + 
  labs(title = "Common Garden Fitness vs Genomic Offset (RDA, Full): \nBinary Survival",
       x = "RDA offset", y = "Survival") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21)))+
  theme_minimal()
surv_full_bin_cg_rda

surv_mll_bin_cg_rda <- surv_all_go_mll %>% 
  filter(method == "rda") %>% 
  ggplot(aes(x = offset, y = surv, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "lm", se = T) + 
  labs(title = "Common Garden Fitness vs Genomic Offset (RDA, MLL): \nBinary Survival",
       x = "RDA offset", y = "Survival") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
surv_mll_bin_cg_rda
####################

# logistic regression
#####################
surv_full_binlog_cg_rda <- surv_all_go_full %>% 
  filter(method == "rda") %>% 
  ggplot(aes(x = offset, y = surv, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "glm", method.args = list(family = "binomial"), se = T) + 
  labs(title = "Common Garden Fitness vs Genomic Offset (RDA, Full): \nBinary Survival, Logistic Regression",
       x = "RDA offset", y = "Survival") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21)))+
  theme_minimal()
surv_full_binlog_cg_rda

surv_mll_binlog_cg_rda <- surv_all_go_mll %>% 
  filter(method == "rda") %>% 
  ggplot(aes(x = offset, y = surv, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "glm", method.args = list(family = "binomial"), se = T) + 
  labs(title = "Common Garden Fitness vs Genomic Offset (RDA, MLL): \nBinary Survival, Logistic Regression",
       x = "RDA offset", y = "Survival") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
surv_mll_binlog_cg_rda
####################

# current future: RDA
#####################
surv_full_bin_cf_rda <- surv_all_go_full %>% 
  filter(method == "rda") %>% 
  ggplot(aes(x = offset, y = surv, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "lm", se = F) + 
  labs(title = "Current-Future Fitness vs Genomic Offset (RDA, Full): \nBinary Survival", 
       x = "RDA offset", y = "Survival") +
  scale_fill_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
surv_full_bin_cf_rda

surv_mll_bin_cf_rda <- surv_all_go_mll %>% 
  filter(method == "rda") %>% 
  ggplot(aes(x = offset, y = surv, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "lm", se = F) + 
  labs(title = "Current-Future Fitness vs Genomic Offset (RDA, MLL): \nBinary Survival", 
       x = "RDA offset", y = "Survival") +
  scale_fill_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
surv_mll_bin_cf_rda
#####################

## logistic
###########
surv_full_binlog_cf_rda <- surv_all_go_full %>% 
  filter(method == "rda") %>% 
  ggplot(aes(x = offset, y = surv, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "glm", method.args = list(family = "binomial"), se = F) + 
  labs(title = "Current-Future Fitness vs Genomic Offset (RDA, Full): \nBinary Survival, Logistic Regression", 
       x = "RDA offset", y = "Survival") +
  scale_fill_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
surv_full_binlog_cf_rda

surv_mll_binlog_cf_rda <- surv_all_go_mll %>% 
  filter(method == "rda") %>% 
  ggplot(aes(x = offset, y = surv, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "glm", method.args = list(family = "binomial"), se = F) + 
  labs(title = "Current-Future Fitness vs Genomic Offset (RDA, MLL): \nBinary Survival, Logistic Regression", 
       x = "RDA offset", y = "Survival") +
  scale_fill_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
surv_mll_binlog_cf_rda
###########
```

Gradient Forest

```{r}
# proportions
# common garden: GF
###################
surv_full_cg_gf <- surv_go_full %>% ggplot(aes(x = gf_offset, y = surv, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "lm", se = T) + 
  labs(title = "Common Garden Fitness vs Genomic Offset (GF, Full): Survival",
       x = "GF offset", y = "Survival") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
surv_full_cg_gf

surv_mll_cg_gf <- surv_go_mll %>% ggplot(aes(x = gf_offset, y = surv, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "lm", se = T) + 
  labs(title = "Common Garden Fitness vs Genomic Offset (GF, MLL): Survival",
       x = "GF offset", y = "Survival") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
surv_mll_cg_gf
###################

# current future: GF
####################
surv_full_cf_gf <- surv_go_full %>% ggplot(aes(x = gf_offset, y = surv, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "lm", se = F) + 
  labs(title = "Current-Future Fitness vs Genomic Offset (GF, Full): Survival", 
       x = "GF offset", y = "Survival") +
  scale_fill_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
surv_full_cf_gf

surv_mll_cf_gf <- surv_go_mll %>% ggplot(aes(x = gf_offset, y = surv, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "lm", se = F) + 
  labs(title = "Current-Future Fitness vs Genomic Offset (GF, MLL): Survival", 
       x = "GF offset", y = "Survival") +
  scale_fill_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
surv_mll_cf_gf
####################

# binary
# common garden: GF
###################
surv_full_bin_cg_gf <- surv_all_go_full %>% 
  filter(method == "gf") %>% 
  ggplot(aes(x = offset, y = surv, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "lm", se = T) + 
  labs(title = "Common Garden Fitness vs Genomic Offset (GF, Full): \nBinary Survival",
       x = "GF offset", y = "Survival") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
surv_full_bin_cg_gf

surv_mll_bin_cg_gf <- surv_all_go_mll %>% 
  filter(method == "gf") %>% 
  ggplot(aes(x = offset, y = surv, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "lm", se = T) + 
  labs(title = "Common Garden Fitness vs Genomic Offset (GF, MLL): \nBinary Survival",
       x = "GF offset", y = "Survival") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
surv_mll_bin_cg_gf
###################

# logistic regression
#####################
surv_full_binlog_cg_gf <- surv_all_go_full %>% 
  filter(method == "gf") %>% 
  ggplot(aes(x = offset, y = surv, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "glm", method.args = list(family = "binomial"), se = T) + 
  labs(title = "Common Garden Fitness vs Genomic Offset (GF, Full): \nBinary Survival, Logistic Regression",
       x = "GF offset", y = "Survival") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
surv_full_binlog_cg_gf

surv_mll_binlog_cg_gf <- surv_all_go_mll %>% 
  filter(method == "gf") %>% 
  ggplot(aes(x = offset, y = surv, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "glm", method.args = list(family = "binomial"), se = T) + 
  labs(title = "Common Garden Fitness vs Genomic Offset (GF, MLL): \nBinary Survival, Logistic Regression",
       x = "GF offset", y = "Survival") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
surv_mll_binlog_cg_gf
#####################

# current future: GF
####################
surv_full_bin_cf_gf <- surv_all_go_full %>% 
  filter(method == "gf") %>% 
  ggplot(aes(x = offset, y = surv, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "lm", se = F) + 
  labs(title = "Current-Future Fitness vs Genomic Offset (GF, Full): \nBinary Survival", 
       x = "GF offset", y = "Survival") +
  scale_fill_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
surv_full_bin_cf_gf

surv_mll_bin_cf_gf <- surv_all_go_mll %>% 
  filter(method == "gf") %>% 
  ggplot(aes(x = offset, y = surv, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "lm", se = F) + 
  labs(title = "Current-Future Fitness vs Genomic Offset (GF, MLL): \nBinary Survival", 
       x = "GF offset", y = "Survival") +
  scale_fill_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
surv_mll_bin_cf_gf
####################

# logistic
##########
surv_full_binlog_cf_gf <- surv_all_go_full %>% 
  filter(method == "gf") %>% 
  ggplot(aes(x = offset, y = surv, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "glm", method.args = list(family = "binomial"), se = F) + 
  labs(title = "Current-Future Fitness vs Genomic Offset (GF, Full): \nBinary Survival, Logistic Regression", 
       x = "GF offset", y = "Survival") +
  scale_fill_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
surv_full_binlog_cf_gf

surv_mll_binlog_cf_gf <- surv_all_go_mll %>% 
  filter(method == "gf") %>% 
  ggplot(aes(x = offset, y = surv, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "glm", method.args = list(family = "binomial"), se = F) + 
  labs(title = "Current-Future Fitness vs Genomic Offset (GF, MLL): \nBinary Survival, Logistic Regression", 
       x = "GF offset", y = "Survival") +
  scale_fill_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
surv_mll_binlog_cf_gf
##########
```

Env Dist

```{r}
# means by pop/treatment
# common garden: LEA
####################
surv_full_cg_lea <- surv_go_full %>% ggplot(aes(x = lea_offset, y = surv, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "lm", se = T) + 
  labs(title = "Common Garden Fitness vs Genomic Offset (LEA, Full): Survival",
       x = "LEA offset", y = "Survival") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21)))+
  theme_minimal()
surv_full_cg_lea
surv_mll_cg_lea <- surv_go_mll %>% ggplot(aes(x = lea_offset, y = surv, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "lm", se = T) + 
  labs(title = "Common Garden Fitness vs Genomic Offset (LEA, MLL): Survival",
       x = "LEA offset", y = "Survival") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21)))+
  theme_minimal()
surv_mll_cg_lea
####################

# current future: LEA
#####################
surv_full_cf_lea <- surv_go_full %>% ggplot(aes(x = lea_offset, y = surv, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "lm", se = F) + 
  labs(title = "Current-Future Fitness vs Genomic Offset (LEA, Full): Survival", 
       x = "LEA offset", y = "Survival") +
  scale_fill_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
surv_full_cf_lea
surv_mll_cf_lea <- surv_go_mll %>% ggplot(aes(x = lea_offset, y = surv, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "lm", se = F) + 
  labs(title = "Current-Future Fitness vs Genomic Offset (LEA, MLL): Survival", 
       x = "LEA offset", y = "Survival") +
  scale_fill_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
surv_mll_cf_lea
#####################

# binary outcome
# common garden: LEA
####################
surv_full_bin_cg_lea <- surv_all_go_full %>% 
  filter(method == "lea") %>%
  ggplot(aes(x = offset, y = surv, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "lm", se = T) + 
  labs(title = "Common Garden Fitness vs Genomic Offset (LEA, Full): \nBinary Survival",
       x = "LEA offset", y = "Survival") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21)))+
  theme_minimal()
surv_full_bin_cg_lea
surv_mll_bin_cg_lea <- surv_all_go_mll %>% 
  filter(method == "lea") %>%
  ggplot(aes(x = offset, y = surv, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "lm", se = T) + 
  labs(title = "Common Garden Fitness vs Genomic Offset (LEA, MLL): \nBinary Survival",
       x = "LEA offset", y = "Survival") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21)))+
  theme_minimal()
surv_mll_bin_cg_lea
####################

# with log regression
#####################
surv_full_binlog_cg_lea <- surv_all_go_full %>% 
  filter(method == "lea") %>%
  ggplot(aes(x = offset, y = surv, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "glm", method.args = list(family = "binomial"), se = T) + 
  labs(title = "Common Garden Fitness vs Genomic Offset (LEA, Full): \nBinary Survival, Logistic Regression",
       x = "LEA offset", y = "Survival") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21)))+
  theme_minimal()
surv_full_binlog_cg_lea

surv_mll_binlog_cg_lea <- surv_all_go_mll %>% 
  filter(method == "lea") %>%
  ggplot(aes(x = offset, y = surv, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "glm", method.args = list(family = "binomial"), se = T) + 
  labs(title = "Common Garden Fitness vs Genomic Offset (LEA, MLL): \nBinary Survival, Logistic Regression",
       x = "LEA offset", y = "Survival") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21)))+
  theme_minimal()
surv_mll_binlog_cg_lea
#####################

# current future: LEA
#####################
surv_full_bin_cf_lea <- surv_all_go_full %>%
  filter(method == "lea") %>%
  ggplot(aes(x = offset, y = surv, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "lm", se = F) + 
  labs(title = "Current-Future Fitness vs Genomic Offset (LEA, Full): \nBinary Survival", 
       x = "LEA offset", y = "Survival") +
  scale_fill_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
surv_full_bin_cf_lea

surv_mll_bin_cf_lea <- surv_all_go_mll %>% 
  filter(method == "lea") %>%
  ggplot(aes(x = offset, y = surv, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "lm", se = F) + 
  labs(title = "Current-Future Fitness vs Genomic Offset (LEA, MLL): \nBinary Survival", 
       x = "LEA offset", y = "Survival") +
  scale_fill_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
surv_mll_bin_cf_lea
#####################

# with log regression
#####################
surv_full_binlog_cf_lea <- surv_all_go_full %>%
  filter(method == "lea") %>%
  ggplot(aes(x = offset, y = surv, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "glm", method.args = list(family = "binomial"), se = F) + 
  labs(title = "Current-Future Fitness vs Genomic Offset (LEA, Full): \nBinary Survival, Logistic Regression", 
       x = "LEA offset", y = "Survival") +
  scale_fill_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
surv_full_binlog_cf_lea

surv_mll_binlog_cf_lea <- surv_all_go_mll %>% 
  filter(method == "lea") %>%
  ggplot(aes(x = offset, y = surv, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "glm", method.args = list(family = "binomial"), se = F) + 
  labs(title = "Current-Future Fitness vs Genomic Offset (LEA, MLL): \nBinary Survival, Logistic Regression", 
       x = "LEA offset", y = "Survival") +
  scale_fill_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
surv_mll_binlog_cf_lea
#####################
```

### Length

LEA

```{r}
# common garden: LEA
####################
len_full_cg_lea <- grow_go_full %>% ggplot(aes(x = lea_offset, y = length_std_change, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "lm", se = T) + 
  labs(title = "Common Garden Fitness vs Genomic Offset (LEA, Full): Length",
       x = "LEA offset", y = "Length") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
len_full_cg_lea

len_mll_cg_lea <- grow_go_mll %>% ggplot(aes(x = lea_offset, y = length_std_change, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "lm", se = T) + 
  labs(title = "Common Garden Fitness vs Genomic Offset (LEA, MLL): Length",
       x = "LEA offset", y = "Length") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
len_mll_cg_lea
####################

# current future: LEA
#####################
len_full_cf_lea <- grow_go_full %>% ggplot(aes(x = lea_offset, y = length_std_change, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "lm", se = F) + 
  labs(title = "Current-Future Fitness vs Genomic Offset (LEA, Full): Length", 
       x = "LEA offset", y = "Length") +
  scale_fill_manual(name = "Population",
                    values = c("#155d27","#25a244","#4ad66d","#b7efc5", 
                               "#82daff","#0078cf","#0130b9","#002e5a"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#155d27","#25a244","#4ad66d","#b7efc5", 
                               "#82daff","#0078cf","#0130b9","#002e5a"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
len_full_cf_lea

len_mll_cf_lea <- grow_go_mll %>% ggplot(aes(x = lea_offset, y = length_std_change, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "lm", se = F) + 
  labs(title = "Current-Future Fitness vs Genomic Offset (LEA, MLL): Length", 
       x = "LEA offset", y = "Length") +
  scale_fill_manual(name = "Population",
                    values = c("#155d27","#25a244","#4ad66d","#b7efc5", 
                               "#82daff","#0078cf","#0130b9","#002e5a"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#155d27","#25a244","#4ad66d","#b7efc5", 
                               "#82daff","#0078cf","#0130b9","#002e5a"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
len_mll_cf_lea
#####################
```

RDA

```{r}
# common garden: RDA
####################
len_full_cg_rda <- grow_go_full %>% ggplot(aes(x = rda_offset, y = length_std_change, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "lm", se = T) + 
  labs(title = "Common Garden Fitness vs Genomic Offset (RDA, Full): Length",
       x = "RDA offset", y = "Length") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
len_full_cg_rda

len_mll_cg_rda <- grow_go_mll %>% ggplot(aes(x = rda_offset, y = length_std_change, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "lm", se = T) + 
  labs(title = "Common Garden Fitness vs Genomic Offset (RDA, MLL): Length",
       x = "RDA offset", y = "Length") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
len_mll_cg_rda
####################

# current future: RDA
#####################
len_full_cf_rda <- grow_go_full %>% ggplot(aes(x = rda_offset, y = length_std_change, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "lm", se = F) + 
  labs(title = "Current-Future Fitness vs Genomic Offset (RDA, Full): Length", 
       x = "RDA offset", y = "Length") +
  scale_fill_manual(name = "Population",
                    values = c("#155d27","#25a244","#4ad66d","#b7efc5", 
                               "#82daff","#0078cf","#0130b9","#002e5a"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#155d27","#25a244","#4ad66d","#b7efc5", 
                               "#82daff","#0078cf","#0130b9","#002e5a"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
len_full_cf_rda

len_mll_cf_rda <- grow_go_mll %>% ggplot(aes(x = rda_offset, y = length_std_change, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "lm", se = F) + 
  labs(title = "Current-Future Fitness vs Genomic Offset (RDA, MLL): Length", 
       x = "RDA offset", y = "Length") +
  scale_fill_manual(name = "Population",
                    values = c("#155d27","#25a244","#4ad66d","#b7efc5", 
                               "#82daff","#0078cf","#0130b9","#002e5a"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#155d27","#25a244","#4ad66d","#b7efc5", 
                               "#82daff","#0078cf","#0130b9","#002e5a"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
len_mll_cf_rda
#####################
```

Gradient Forest

```{r}
# common garden: GF
###################
len_full_cg_gf <- grow_go_full %>% ggplot(aes(x = gf_offset, y = length_std_change, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "lm", se = T) + 
  labs(title = "Common Garden Fitness vs Genomic Offset (GF, Full): Length",
       x = "GF offset", y = "Length") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
len_full_cg_gf

len_mll_cg_gf <- grow_go_mll %>% ggplot(aes(x = gf_offset, y = length_std_change, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "lm", se = T) + 
  labs(title = "Common Garden Fitness vs Genomic Offset (GF, MLL): Length",
       x = "GF offset", y = "Length") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
len_mll_cg_gf
###################

# current future: GF
####################
len_full_cf_gf <- grow_go_full %>% ggplot(aes(x = gf_offset, y = length_std_change, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "lm", se = F) + 
  labs(title = "Current-Future Fitness vs Genomic Offset (GF, Full): Length", 
       x = "GF offset", y = "Length") +
  scale_fill_manual(name = "Population",
                    values = c("#155d27","#25a244","#4ad66d","#b7efc5", 
                               "#82daff","#0078cf","#0130b9","#002e5a"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#155d27","#25a244","#4ad66d","#b7efc5", 
                               "#82daff","#0078cf","#0130b9","#002e5a"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
len_full_cf_gf

len_mll_cf_gf <- grow_go_mll %>% ggplot(aes(x = gf_offset, y = length_std_change, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "lm", se = F) + 
  labs(title = "Current-Future Fitness vs Genomic Offset (GF, MLL): Length", 
       x = "GF offset", y = "Length") +
  scale_fill_manual(name = "Population",
                    values = c("#155d27","#25a244","#4ad66d","#b7efc5", 
                               "#82daff","#0078cf","#0130b9","#002e5a"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#155d27","#25a244","#4ad66d","#b7efc5", 
                               "#82daff","#0078cf","#0130b9","#002e5a"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
len_mll_cf_gf
####################
```

Env Dist

```{r}
# common garden: env dist
#########################
len_cg_env <- grow_go_full %>% ggplot(aes(x = env_dist, y = length_std_change, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "lm", se = T) + 
  labs(title = "Common Garden Fitness vs Environmental Distance: Length",
       x = "Environmental Distance", y = "Length") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
len_cg_env
#########################

# current future: env dist
##########################
len_cf_env <- grow_go_full %>% ggplot(aes(x = env_dist, y = length_std_change, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "lm", se = F) + 
  labs(title = "Current-Future Fitness vs Environmental Distance: Length", 
       x = "Environmental Distance", y = "Length") +
  scale_fill_manual(name = "Population",
                    values = c("#155d27","#25a244","#4ad66d","#b7efc5", 
                               "#82daff","#0078cf","#0130b9","#002e5a"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#155d27","#25a244","#4ad66d","#b7efc5", 
                               "#82daff","#0078cf","#0130b9","#002e5a"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
len_cf_env
##########################
```


### Weight

LEA

```{r}
# common garden: LEA
####################
weigh_full_cg_lea <- grow_go_full %>% ggplot(aes(x = lea_offset, y = weight_std_change, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "lm", se = T) + 
  labs(title = "Common Garden Fitness vs Genomic Offset (LEA, Full): Weight",
       x = "LEA offset", y = "Weight") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
weigh_full_cg_lea

weigh_mll_cg_lea <- grow_go_mll %>% ggplot(aes(x = lea_offset, y = weight_std_change, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "lm", se = T) + 
  labs(title = "Common Garden Fitness vs Genomic Offset (LEA, MLL): Weight",
       x = "LEA offset", y = "Weight") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
weigh_mll_cg_lea
####################

# current future: LEA
#####################
weigh_full_cf_lea <- grow_go_full %>% ggplot(aes(x = lea_offset, y = weight_std_change, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "lm", se = F) + 
  labs(title = "Current-Future Fitness vs Genomic Offset (LEA, Full): Weight", 
       x = "LEA offset", y = "Weight") +
  scale_fill_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
weigh_full_cf_lea

weigh_mll_cf_lea <- grow_go_mll %>% ggplot(aes(x = lea_offset, y = weight_std_change, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "lm", se = F) + 
  labs(title = "Current-Future Fitness vs Genomic Offset (LEA, MLL): Weight", 
       x = "LEA offset", y = "Weight") +
  scale_fill_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
weigh_mll_cf_lea
#####################
```

RDA

```{r}
# common garden: RDA
####################
weigh_full_cg_rda <- grow_go_full %>% ggplot(aes(x = rda_offset, y = weight_std_change, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "lm", se = T) + 
  labs(title = "Common Garden Fitness vs Genomic Offset (RDA, Full): Weight",
       x = "RDA offset", y = "Weight") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
weigh_full_cg_rda

weigh_mll_cg_rda <- grow_go_mll %>% ggplot(aes(x = rda_offset, y = weight_std_change, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "lm", se = T) + 
  labs(title = "Common Garden Fitness vs Genomic Offset (RDA, MLL): Weight",
       x = "RDA offset", y = "Weight") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
weigh_mll_cg_rda
####################

# current future: RDA
#####################
weigh_full_cf_rda <- grow_go_full %>% ggplot(aes(x = rda_offset, y = weight_std_change, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "lm", se = F) + 
  labs(title = "Current-Future Fitness vs Genomic Offset (RDA, Full): Weight", 
       x = "RDA offset", y = "Weight") +
  scale_fill_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
weigh_full_cf_rda

weigh_mll_cf_rda <- grow_go_mll %>% ggplot(aes(x = rda_offset, y = weight_std_change, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "lm", se = F) + 
  labs(title = "Current-Future Fitness vs Genomic Offset (RDA, MLL): Weight", 
       x = "RDA offset", y = "Weight") +
  scale_fill_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
weigh_mll_cf_rda
#####################
```

Gradient Forest

```{r}
# common garden: GF
###################
weigh_full_cg_gf <- grow_go_full %>% ggplot(aes(x = gf_offset, y = weight_std_change, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "lm", se = T) + 
  labs(title = "Common Garden Fitness vs Genomic Offset (GF, Full): Weight",
       x = "GF offset", y = "Weight") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
weigh_full_cg_gf

weigh_mll_cg_gf <- grow_go_mll %>% ggplot(aes(x = gf_offset, y = weight_std_change, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "lm", se = T) + 
  labs(title = "Common Garden Fitness vs Genomic Offset (GF, MLL): Weight",
       x = "GF offset", y = "Weight") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
weigh_mll_cg_gf
###################

# current future: GF
####################
weigh_full_cf_gf <- grow_go_full %>% ggplot(aes(x = gf_offset, y = weight_std_change, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "lm", se = F) + 
  labs(title = "Current-Future Fitness vs Genomic Offset (GF, Full): Weight", 
       x = "GF offset", y = "Weight") +
  scale_fill_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
weigh_full_cf_gf

weigh_mll_cf_gf <- grow_go_mll %>% ggplot(aes(x = gf_offset, y = weight_std_change, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "lm", se = F) + 
  labs(title = "Current-Future Fitness vs Genomic Offset (GF, MLL): Weight", 
       x = "GF offset", y = "Weight") +
  scale_fill_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
weigh_mll_cf_gf
####################
```

Environmental Distance

```{r}
# common garden: env dist
#########################
weigh_cg_env <- grow_go_full %>% ggplot(aes(x = env_dist, y = weight_std_change, fill = fct_reorder(trt, trt_ord), shape = fct_reorder(trt_coast, trt_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = trt), method = "lm", se = T) + 
  labs(title = "Common Garden Fitness vs Environmental Distance: Weight",
       x = "Environmental Distance", y = "Weight") +
  scale_fill_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_colour_manual(name = "Treatment",
                    values = c("#FFA203","#FE691E","deeppink","deeppink4"),
                    labels = c("Current W Coast", "Current E Coast",
                               "Future W Coast", "Future E Coast")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
weigh_cg_env
#########################

# current future: env dist
##########################
weigh_cf_env <- grow_go_full %>% ggplot(aes(x = env_dist, y = weight_std_change, fill = fct_reorder(pop, pop_ord), shape = fct_reorder(pop_coast, pop_coast_ord))) +
  geom_point(size = 4) + 
  geom_smooth(aes(col = fct_reorder(pop, pop_ord)), method = "lm", se = F) + 
  labs(title = "Current-Future Fitness vs Environmental Distance: Weight", 
       x = "Environmental Distance", y = "Weight") +
  scale_fill_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_colour_manual(name = "Population",
                    values = c("#002e5a","#0130b9","#0078cf","#82daff", 
                               "#d9ed92","#4ad66d","#25a244","#155d27"),
                    labels = c("VIK","VAT","HOG","BAR","KUR","KAL","HOR","BJO")) +
  scale_shape_manual(name = "Coast",
                    values = c(21, 24),
                    labels = c("West Coast", "East Coast")) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_minimal()
weigh_cf_env
##########################
```


### Export

```{r}
# single figure
library(gridExtra)

grid.arrange(surv_full_binlog_cg_lea, surv_full_binlog_cf_lea, surv_full_binlog_cg_rda, surv_full_binlog_cf_rda, surv_full_binlog_cg_gf, surv_full_binlog_cf_gf, ncol = 2)

doc <- read_pptx() %>% 
  add_slide(layout = "Title and Content", master = "Office Theme") %>% 
  ph_with(value = dml(ggobj = surv_full_binlog_cg_lea), location = ph_location_type(type = "body")) %>%
  add_slide(layout = "Title and Content", master = "Office Theme") %>% 
  ph_with(value = dml(ggobj = surv_full_binlog_cf_lea), location = ph_location_type(type = "body")) %>%
  add_slide(layout = "Title and Content", master = "Office Theme") %>% 
  ph_with(value = dml(ggobj = surv_full_binlog_cg_rda), location = ph_location_type(type = "body")) %>%
  add_slide(layout = "Title and Content", master = "Office Theme") %>% 
  ph_with(value = dml(ggobj = surv_full_binlog_cf_rda), location = ph_location_type(type = "body")) %>%
  add_slide(layout = "Title and Content", master = "Office Theme") %>% 
  ph_with(value = dml(ggobj = surv_full_binlog_cg_gf), location = ph_location_type(type = "body")) %>%
  add_slide(layout = "Title and Content", master = "Office Theme") %>% 
  ph_with(value = dml(ggobj = surv_full_binlog_cf_gf), location = ph_location_type(type = "body"))
print(doc, target = "results/figures/offsets_compare_poptrt_surv.pptx")
```
