---
title: "eelgrass_fitness_calc"
author: "Camille Rumberger"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/Documents/Github/BalticEelgrass")

# setwd
setwd("/Users/camillerumberger/Documents/GitHub/BalticEelgrass")

# libraries
library(tidyverse)
library(stringr)
library(ggplot2)
library(viridis)

# data
fit <- read.csv("data/experiment/eelgrass_mesocosm_start_end_complete.csv")[,-1]
exp_pops <- read.csv("data/experiment/eelgrass_exp_sites.csv")
```

# Fitness Calculation

This script is to calculate survival and growth in the mesocosm experiments. 

## Data processing

```{r data pre-process}
# data cleaning to just relevant columns
fit_trim <- fit[,c("DNA_label", "new_label", "pop", "genet", "bagnum", "tank_ID", "sal_full", "temp_full", "trt", "nbr_leaves_start", "sideShoot", "nbr_sideShootLeaves_start", "length_longest_leaf_start", "weight_start", "IsBlackLesions_start", "nbr_leaves_end", "nbr_new_leaves", "width_leaf", "Growth_leaf1", "Growth_leaf2", "Growth_leaf3", "Growth_leaf4", "Growth_leaf5", "Growth_leaf6", "Growth_leaf7", "Length_new_leaf1", "Length_new_leaf2", "Length_new_leaf3", "Length_new_leaf4", "Length_new_leaf5", "Length_new_leaf6", "Nbr_new_shoots", "Nbr_leaves_new_shoot1", "Length_new_shoot1_leaf1", "Length_new_shoot1_leaf2", "Length_new_shoot1_leaf3", "Length_new_shoot1_leaf4", "Length_new_shoot1_leaf5", "Length_new_shoot1_leaf6", "Nbr_leaves_new_shoot2", "Length_new_shoot2_leaf1", "Length_new_shoot2_leaf2", "Length_new_shoot2_leaf3", "Length_new_shoot2_leaf4", "Length_new_shoot2_leaf5", "below_ground_weight", "above_ground_weight", "weight_new_shoot1", "weight_new_shoot2", "total_weight", "lesions.", "isAlive", "Length_flower1", "Length_bract1")]

# binary survival column
fit_trim$isAlive <- ifelse(fit_trim$isAlive == TRUE, 1, 0)

# pop_trt factor for later significance testing
fit_trim$pop_trt <- as.factor(paste0(fit_trim$pop, "_", fit_trim$trt))

# length and weight growth
# for the growth analyses, we want a df with no flowering individuals and no dead individuals
fit_growth <- fit_trim_env[is.na(fit_trim_env$Length_flower1),]
fit_growth <- fit_growth[fit_growth$isAlive == 1,]

# standardized growth variables
# length
fit_growth$length_growth <- rowSums(fit_growth[,c("Growth_leaf1", "Growth_leaf2", "Growth_leaf3", "Growth_leaf4", "Growth_leaf5", "Growth_leaf6", "Growth_leaf7", "Length_new_leaf1", "Length_new_leaf2", "Length_new_leaf3", "Length_new_leaf4", "Length_new_leaf5", "Length_new_leaf6", "Length_new_shoot1_leaf1", "Length_new_shoot1_leaf2", "Length_new_shoot1_leaf3", "Length_new_shoot1_leaf4", "Length_new_shoot1_leaf5", "Length_new_shoot1_leaf6", "Length_new_shoot2_leaf1", "Length_new_shoot2_leaf2", "Length_new_shoot2_leaf3", "Length_new_shoot2_leaf4", "Length_new_shoot2_leaf5")], na.rm = T)

# standardized length growth
fit_growth$length_std_change <- fit_growth$length_growth / fit_growth$length_longest_leaf_start

# weight
fit_growth$weight_change <- fit_growth$total_weight - fit_growth$weight_start

# standardized weight change
fit_growth$weight_std_change <- fit_growth$weight_change / fit_growth$weight_start

# ratio of above vs below ground weight
fit_growth$above_below_weight_ratio <- fit_growth$above_ground_weight / fit_growth$below_ground_weight

# save outputs
#write.csv(fit_trim, "data/experiment/expfit_trim.csv", row.names = F)
#write.csv(fit_growth, "data/experiment/expfit_grow_trim.csv", row.names = F)
```

## Fitness Metrics

I will calculate pop/trt level survival, length change, and weight change.

```{r}
# just survival info
fit_surv <- fit_trim[,c("new_label","bagnum","tank_ID","pop","trt","pop_trt","isAlive")]

# calculate survival
surv <- fit_surv %>% 
  group_by(pop, trt) %>% 
  summarize(surv_mean = mean(isAlive), 
            surv_sd = sd(isAlive))

# calc by tank
surv_tank <- fit_surv %>% 
  group_by(pop, trt, tank_ID) %>% 
  summarize(surv_mean = mean(isAlive), 
            surv_sd = sd(isAlive))

# calculate growth
grow <- fit_growth %>% 
  group_by(pop, trt) %>% 
  summarize(len_mean = mean(length_std_change, na.rm = T), 
            len_sd = sd(length_std_change, na.rm = T), 
            weigh_mean = mean(weight_std_change, na.rm = T), 
            weigh_sd = sd(weight_std_change, na.rm = T))


# calc by tank
grow_tank <- fit_growth %>% 
  group_by(pop, trt, tank_ID) %>% 
  summarize(len_mean = mean(length_std_change, na.rm = T), 
            len_sd = sd(length_std_change, na.rm = T), 
            weigh_mean = mean(weight_std_change, na.rm = T), 
            weigh_sd = sd(weight_std_change, na.rm = T))

# put it together
expfit <- merge(surv, grow, by = c("pop", "trt"), all = T)
expfit_tank <- merge(surv_tank, grow_tank, by = c("pop", "trt", "tank_ID"), all = T)

# add pop info
exp_pops$pop_order <- 1:8
exp_pops$pop <- exp_pops$site_abbrev
expfit_mg <- merge(exp_pops, expfit, by = "pop")
expfit_mg$trt <- gsub("_", "-", expfit_mg$trt)
expfit_tank_mg <- merge(exp_pops, expfit_tank, by = "pop")
expfit_tank_mg$trt <- gsub("_", "-", expfit_tank_mg$trt)
write.csv(expfit_mg, "data/experiment/expfit_poptrt.csv", row.names = F)
write.csv(expfit_tank_mg, "data/experiment/expfit_tank_poptrt.csv", row.names = F)
```

## Plotting

Plotting averages

```{r}
# better trt names
trt_names2 <- c("TempControl-21psu" = "Current W Coast", "TempControl-7psu" = "Current E Coast", "TempWarm-16psu" = "Future W Coast", "TempWarm-5psu" = "Future E Coast")
trt_ord2 <- c("TempControl-21psu" = 1, "TempControl-7psu" = 2, "TempWarm-16psu" = 3, "TempWarm-5psu" = 4)
expfit_mg <- expfit_mg %>% mutate(trt_name = trt_names2[trt], trt_order = trt_ord2[trt]) 
expfit_mg$trt_name <- unname(expfit_mg$trt_name)
expfit_mg$trt_order <- unname(expfit_mg$trt_order)

# survival
surv_avg_heatmap <- ggplot(expfit_mg, aes(x = fct_reorder(pop, pop_order), y = fct_reorder(trt_name, trt_order), fill = surv_mean)) +
  geom_tile(color = "white") +
  scale_fill_viridis_c(option = "viridis", direction = 1, limits = c(0,1), na.value = "white") +
  theme_classic() +
  labs(title = "Survival in Mesocosm Treatments", x = "Population", y = "Treatment", fill = "Survival")
surv_avg_heatmap

# length
len_avg_heatmap <- ggplot(expfit_mg, aes(x = fct_reorder(pop, pop_order), fct_reorder(trt_name, trt_order), fill = len_mean)) +
  geom_tile(color = "white") +
  scale_fill_viridis_c(option = "viridis", direction = 1, limits = c(0,5), na.value = "white") +
  theme_classic() +
  labs(title = "Length Change in Mesocosm Treatments", x = "Population", y = "Treatment", fill = "∆Length")
len_avg_heatmap

# weight
weight_avg_heatmap <- ggplot(expfit_mg, aes(x = fct_reorder(pop, pop_order), fct_reorder(trt_name, trt_order), fill = weigh_mean)) +
  geom_tile(color = "white") +
  scale_fill_viridis_c(option = "viridis", direction = 1, limits = c(-0.7,0.4), na.value = "white") +
  theme_classic() +
  labs(title = "Weight Change in Mesocosm Treatments", x = "Population", y = "Treatment", fill = "∆Weight")
weight_avg_heatmap
```

Plotting common garden vs current future comparisons

```{r}
## survival
###########
trt_labels <- c("TempControl-21psu" = "Current W Coast", "TempControl-7psu" = "Current E Coast",  "TempWarm-16psu" = "Future W Coast", "TempWarm-5psu" = "Future E Coast")
pop_colors <- c(VIK = "#002e5a", VAT = "#0130b9", HOG = "#0078cf", BAR = "#82daff", KUR = "#d9ed92", KAL = "#4ad66d", HOR = "#25a244", BJO = "#155d27")
trt_colors <- c("Current W Coast" = "#FFA203", "Current E Coast" = "#FE691E",  "Future W Coast" = "deeppink", "Future E Coast" = "deeppink4")
trt_order <- c("Current W Coast", "Current E Coast", "Future W Coast", "Future E Coast")
expfit_mg$trt_factor <- factor(expfit_mg$trt_name, levels = trt_order)
expfit_mg$pop_factor <- factor(expfit_mg$pop, levels = names(pop_colors))

# pop x trt
poptrt_surv_cf <- ggplot(expfit_mg, aes(x = pop_factor, y = surv_mean, fill = trt_factor)) +
  theme_classic() +
  geom_bar(stat = "identity", position = "dodge", color = "black") +
  scale_fill_manual(name = "Treatment",
                    values = trt_colors,
                    labels = trt_labels,
                    breaks = names(trt_colors)) +
  theme(plot.title = element_text(size = 24), 
        plot.subtitle = element_text(size = 15),
        legend.title = element_text(size = 15),
        legend.position = "right") +
  xlab("Population") +
  ylab("Survival") +
  ggtitle("Survival by Population & Treatment", subtitle = "Current Future Comparison")
poptrt_surv_cf

# pop x trt
poptrt_surv_cg <- ggplot(expfit_mg, aes(x = trt_factor, y = surv_mean, fill = pop_factor)) +
  geom_bar(stat = "identity", position = "dodge")+
  theme_classic() +
  geom_bar(stat = "identity", position = "dodge", color = "black") +
  scale_fill_manual(name = "Population",
                    values = pop_colors,
                    breaks = names(pop_colors)) +
  theme(plot.title = element_text(size = 24), 
        plot.subtitle = element_text(size = 15),
        legend.title = element_text(size = 15),
        legend.position = "right") +
  xlab("Population") + 
  ylab("Survival") +
  ggtitle("Survival by Treatment & Population", subtitle = "Common Garden Comparison")
poptrt_surv_cg
###########

## length
#########
# pop x trt
poptrt_len_cf <- ggplot(expfit_mg, aes(x = pop_factor, y = len_mean, fill = trt_factor)) +
  theme_classic() +
  geom_bar(stat = "identity", position = "dodge", color = "black") +
  scale_fill_manual(name = "Treatment",
                    values = trt_colors,
                    labels = trt_labels) +
  theme(plot.title = element_text(size = 24), 
        plot.subtitle = element_text(size = 15),
        legend.title = element_text(size = 15),
        legend.position = "right") +
  xlab("Population") + 
  ylab("∆Length (cm)") +
  ggtitle("Length Change by Population & Treatment", subtitle = "Current-Future Comparison")
poptrt_len_cf

# pop x trt
poptrt_len_cg <- ggplot(expfit_mg, aes(x = trt_factor, y = len_mean, fill = pop_factor)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_classic() +
  geom_bar(stat = "identity", position = "dodge", color = "black") +
  scale_fill_manual(name = "Population",
                    values = pop_colors) +
  theme(plot.title = element_text(size = 24), 
        plot.subtitle = element_text(size = 15),
        legend.title = element_text(size = 15),
        legend.position = "right") +
  xlab("Population") + 
  ylab("∆Length (cm)") +
  ggtitle("Length Change by Treatment & Population", subtitle = "Common Garden Comparison")
poptrt_len_cg
#########

## weight chg
#############
# pop x trt
poptrt_weight_cf <- ggplot(expfit_mg, aes(x = pop_factor, y = weigh_mean, fill = trt_factor)) +
  theme_classic() +
  geom_bar(stat = "identity", position = "dodge", color = "black") +
  scale_fill_manual(name = "Treatment",
                    values = trt_colors,
                    labels = trt_labels) +
  theme(plot.title = element_text(size = 24), 
        plot.subtitle = element_text(size = 15),
        legend.title = element_text(size = 15),
        legend.position = "right") +
  xlab("Population") + 
  ylab("∆Weight (g)") +
  ggtitle("Weight Change by Population & Treatment", subtitle = "Current-Future Comparison")
poptrt_weight_cf

# pop x trt
poptrt_weight_cg <- ggplot(expfit_mg, aes(x = trt_factor, y = weigh_mean, fill = pop_factor)) +
  theme_classic() +
  geom_bar(stat = "identity", position = "dodge", color = "black") +
  scale_fill_manual(name = "Population",
                    values = pop_colors) +
  theme(plot.title = element_text(size = 24), 
        plot.subtitle = element_text(size = 15),
        legend.title = element_text(size = 15),
        legend.position = "right") +
  xlab("Population") + 
  ylab("∆Weight (g)") +
  ggtitle("Weight Change by Treatment & Population", subtitle = "Common Garden Comparison")
poptrt_weight_cg
#############
```

Plotting climate change comparisons only

```{r}
## survival
###########
# clim chg df
expfit_mg_w <- expfit_mg %>% filter(pop %in% c("VAT", "VIK", "HOG", "BAR") & trt %in% c("TempControl-21psu", "TempWarm-16psu")) %>% mutate(coast = "West", cf = ifelse(trt == "TempControl-21psu", "Current", "Future"), coast_ord = 1)
expfit_mg_e <- expfit_mg %>% filter(!(pop %in% c("VAT", "VIK", "HOG", "BAR")) & !(trt %in% c("TempControl-21psu", "TempWarm-16psu"))) %>% mutate(coast = "East", cf = ifelse(trt == "TempControl-7psu", "Current", "Future"), coast_ord = 2)
expfit_mg_clim <- rbind(expfit_mg_w, expfit_mg_e)
cf_colors <- c("Current" = "#8C96C6", "Future" = "#4D004B")
#cf_colors <- c("Current" = "#FFEDA0", "Future" = "#800026")

# pop x trt
poptrt_surv_cf_clim <- expfit_mg_clim %>% ggplot(aes(x = pop_factor, y = surv_mean, fill = cf)) +
  theme_classic() +
  geom_bar(stat = "identity", position = "dodge", color = "black") +
  scale_fill_manual(name = "Treatment",
                    values = cf_colors,
                    labels = names(cf_colors),
                    breaks = names(cf_colors)) +
  theme(plot.title = element_text(size = 24), 
        plot.subtitle = element_text(size = 15),
        legend.title = element_text(size = 15),
        legend.position = "right") +
  labs(title = "Experimental Survival", subtitle = "Current-Future", x = "Population", y = "Survival", fill = "Treatment") 
poptrt_surv_cf_clim

# pop x trt
poptrt_surv_cg_clim <- ggplot(expfit_mg_clim, aes(x = cf, y = surv_mean, fill = pop_factor)) +
  geom_bar(stat = "identity", position = "dodge")+
  theme_classic() +
  geom_bar(stat = "identity", position = "dodge", color = "black") +
  scale_fill_manual(name = "Population",
                    values = pop_colors,
                    breaks = names(pop_colors)) +
  theme(plot.title = element_text(size = 24), 
        plot.subtitle = element_text(size = 15),
        legend.title = element_text(size = 15),
        legend.position = "right") +
  labs(title = "Experimental Survival", subtitle = "Common Garden", x = "Treatment", y = "Survival")
poptrt_surv_cg_clim
###########

## coastal surv
###############
# important note - this uses the mean survival for each population, rather than an averaged binary survival by coast
cf_surv_coast_clim <- expfit_mg_clim %>% ggplot(aes(x = fct_reorder(coast, coast_ord), y = surv_mean, fill = cf)) +
  geom_violin(position = position_dodge(0.8)) + 
  scale_fill_manual(name = "Treatment",
                    values = cf_colors,
                    labels = names(cf_colors),
                    breaks = names(cf_colors)) +
  labs(title = "Experimental Survival by Coast", x = "Coast", y = "Survival") +
  theme_minimal()
cf_surv_coast_clim

# with binary survival
fitsurv_w <- fit_surv %>% filter(pop %in% c("VAT", "VIK", "HOG", "BAR") & trt %in% c("TempControl_21psu", "TempWarm_16psu")) %>% mutate(coast = "West", cf = ifelse(trt == "TempControl_21psu", "Current", "Future"), coast_ord = 1)
fitsurv_e <- fit_surv %>% filter(!(pop %in% c("VAT", "VIK", "HOG", "BAR")) & !(trt %in% c("TempControl_21psu", "TempWarm_16psu"))) %>% mutate(coast = "East", cf = ifelse(trt == "TempControl_7psu", "Current", "Future"), coast_ord = 2)
fitsurv_clim <- rbind(fitsurv_w, fitsurv_e)

cf_binsurv_coast_clim <- fitsurv_clim %>% ggplot(aes(x = fct_reorder(coast, coast_ord), y = isAlive, fill = cf)) +
  geom_violin(position = position_dodge(0.8)) + 
  scale_fill_manual(name = "Treatment",
                    values = cf_colors,
                    labels = names(cf_colors),
                    breaks = names(cf_colors)) +
  labs(title = "Experimental Survival by Coast", x = "Coast", y = "Survival") +
  theme_minimal()
cf_binsurv_coast_clim # useless
###############
```

## Export plots

```{r}
doc <- read_pptx() %>% 
  add_slide(layout = "Title and Content", master = "Office Theme") %>% 
  ph_with(value = dml(ggobj = poptrt_surv_cf), location = ph_location_type(type = "body")) %>%
  add_slide(layout = "Title and Content", master = "Office Theme") %>% 
  ph_with(value = dml(ggobj = poptrt_surv_cg), location = ph_location_type(type = "body")) %>%
  add_slide(layout = "Title and Content", master = "Office Theme") %>% 
  ph_with(value = dml(ggobj = poptrt_len_cf), location = ph_location_type(type = "body")) %>%
  add_slide(layout = "Title and Content", master = "Office Theme") %>% 
  ph_with(value = dml(ggobj = poptrt_len_cg), location = ph_location_type(type = "body")) %>%
  add_slide(layout = "Title and Content", master = "Office Theme") %>% 
  ph_with(value = dml(ggobj = poptrt_weight_cf), location = ph_location_type(type = "body")) %>%
  add_slide(layout = "Title and Content", master = "Office Theme") %>% 
  ph_with(value = dml(ggobj = poptrt_weight_cg), location = ph_location_type(type = "body"))
print(doc, target = "results/figures/exp_fitness_plots.pptx")
```

